# coding: utf-8
"""Waylay Alarms: Query Parameters.

This code was generated from the OpenAPI documentation of 'Waylay Alarms'

version: 1.11.0

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""
