# coding: utf-8
"""Waylay Alarms: Service.

This code was generated from the OpenAPI documentation of 'Waylay Alarms'

version: 1.13.1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

__version__ = "1.13.1.20241025"

from .service import AlarmsService

PLUGINS = [AlarmsService]

__all__ = [
    "__version__",
    "AlarmsService",
]
