# coding: utf-8
"""Waylay Alarms model tests.

This code was generated from the OpenAPI documentation of 'Waylay Alarms'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.alarms.models.a_batch_alarms_specification import (
        ABatchAlarmsSpecification,
    )

    ABatchAlarmsSpecificationAdapter = TypeAdapter(ABatchAlarmsSpecification)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

a_batch_alarms_specification_model_schema = json.loads(
    r"""{
  "title" : "a batch alarms specification",
  "type" : "object",
  "oneOf" : [ {
    "$ref" : "#/components/schemas/BatchUpdateAlarm"
  }, {
    "$ref" : "#/components/schemas/BatchDeleteAlarm"
  } ]
}
""",
    object_hook=with_example_provider,
)
a_batch_alarms_specification_model_schema.update({"definitions": MODEL_DEFINITIONS})

a_batch_alarms_specification_faker = JSF(
    a_batch_alarms_specification_model_schema, allow_none_optionals=1
)


class ABatchAlarmsSpecificationStub:
    """ABatchAlarmsSpecification unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return a_batch_alarms_specification_faker.generate(
            use_defaults=True, use_examples=True
        )

    @classmethod
    def create_instance(cls) -> "ABatchAlarmsSpecification":
        """Create ABatchAlarmsSpecification stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if not json:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                ABatchAlarmsSpecificationAdapter.json_schema(), allow_none_optionals=1
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return ABatchAlarmsSpecificationAdapter.validate_python(
            json, context={"skip_validation": True}
        )
