# coding: utf-8
"""Waylay Alarms model tests.

This code was generated from the OpenAPI documentation of 'Waylay Alarms'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import datetime
import json
import warnings

from typing import (
    Union,
    List,
    Dict,
    Literal,  # >=3.8
)
from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.alarms.models.alarms_timeline_item import AlarmsTimelineItem

    AlarmsTimelineItemAdapter = TypeAdapter(AlarmsTimelineItem)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

alarms_timeline_item_model_schema = json.loads(
    r"""{
  "required" : [ "alarm", "timestamp", "type" ],
  "type" : "object",
  "properties" : {
    "timestamp" : {
      "$ref" : "#/components/schemas/AlarmTimelineTimestamp"
    },
    "type" : {
      "$ref" : "#/components/schemas/AlarmEventType"
    },
    "alarm" : {
      "$ref" : "#/components/schemas/AlarmTimelineInfo"
    }
  }
}
""",
    object_hook=with_example_provider,
)
alarms_timeline_item_model_schema.update({"definitions": MODEL_DEFINITIONS})

alarms_timeline_item_faker = JSF(
    alarms_timeline_item_model_schema, allow_none_optionals=1
)


class AlarmsTimelineItemStub:
    """AlarmsTimelineItem unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return alarms_timeline_item_faker.generate()

    @classmethod
    def create_instance(cls) -> "AlarmsTimelineItem":
        """Create AlarmsTimelineItem stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        return AlarmsTimelineItemAdapter.validate_python(cls.create_json())
