# coding: utf-8
"""Waylay Alarms model tests.

This code was generated from the OpenAPI documentation of 'Waylay Alarms'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import datetime
import json
import warnings

from typing import (
    Union,
    List,
    Dict,
    Literal,  # >=3.8
)
from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.alarms.models.alarm_status import AlarmStatus

    AlarmStatusAdapter = TypeAdapter(AlarmStatus)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

alarm_status_model_schema = json.loads(
    r"""{
  "title" : "AlarmStatus",
  "type" : "string",
  "default" : "ACTIVE",
  "enum" : [ "ACTIVE", "ACKNOWLEDGED", "CLEARED" ]
}
""",
    object_hook=with_example_provider,
)
alarm_status_model_schema.update({"definitions": MODEL_DEFINITIONS})

alarm_status_faker = JSF(alarm_status_model_schema, allow_none_optionals=1)


class AlarmStatusStub:
    """AlarmStatus unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return alarm_status_faker.generate()

    @classmethod
    def create_instance(cls) -> "AlarmStatus":
        """Create AlarmStatus stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        return AlarmStatusAdapter.validate_python(cls.create_json())
