# coding: utf-8
"""Waylay Alarms model tests.

This code was generated from the OpenAPI documentation of 'Waylay Alarms'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.alarms.models.alarm_event_type import AlarmEventType

    AlarmEventTypeAdapter = TypeAdapter(AlarmEventType)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

alarm_event_type_model_schema = json.loads(
    r"""{
  "title" : "AlarmEventType",
  "type" : "string",
  "oneOf" : [ {
    "$ref" : "#/components/schemas/AlarmEventType_oneOf"
  }, {
    "$ref" : "#/components/schemas/AlarmEventType_oneOf_1"
  }, {
    "$ref" : "#/components/schemas/AlarmEventType_oneOf_2"
  } ]
}
""",
    object_hook=with_example_provider,
)
alarm_event_type_model_schema.update({"definitions": MODEL_DEFINITIONS})

alarm_event_type_faker = JSF(alarm_event_type_model_schema, allow_none_optionals=1)


class AlarmEventTypeStub:
    """AlarmEventType unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return alarm_event_type_faker.generate()

    @classmethod
    def create_instance(cls) -> "AlarmEventType":
        """Create AlarmEventType stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        return AlarmEventTypeAdapter.validate_python(cls.create_json())
