# coding: utf-8
"""Waylay Alarms model tests.

This code was generated from the OpenAPI documentation of 'Waylay Alarms'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.alarms.models.alarm_event_changes_inner_type import (
        AlarmEventChangesInnerType,
    )

    AlarmEventChangesInnerTypeAdapter = TypeAdapter(AlarmEventChangesInnerType)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

alarm_event_changes_inner_type_model_schema = json.loads(
    r"""{
  "title" : "AlarmEvent_changes_inner_type",
  "type" : "string",
  "description" : "Indication of what has changed",
  "enum" : [ "io.waylay.alarm.change.severity", "io.waylay.alarm.change.status", "io.waylay.alarm.change.attribute" ]
}
""",
    object_hook=with_example_provider,
)
alarm_event_changes_inner_type_model_schema.update({"definitions": MODEL_DEFINITIONS})

alarm_event_changes_inner_type_faker = JSF(
    alarm_event_changes_inner_type_model_schema, allow_none_optionals=1
)


class AlarmEventChangesInnerTypeStub:
    """AlarmEventChangesInnerType unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return alarm_event_changes_inner_type_faker.generate()

    @classmethod
    def create_instance(cls) -> "AlarmEventChangesInnerType":
        """Create AlarmEventChangesInnerType stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        return AlarmEventChangesInnerTypeAdapter.validate_python(cls.create_json())
