# coding: utf-8
"""Waylay Alarms model tests.

This code was generated from the OpenAPI documentation of 'Waylay Alarms'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.alarms.models.alarm_timeline_info import AlarmTimelineInfo

    AlarmTimelineInfoAdapter = TypeAdapter(AlarmTimelineInfo)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

alarm_timeline_info_model_schema = json.loads(
    r"""{
  "required" : [ "creationTime", "id", "severity", "source", "status", "text", "timestamp", "type" ],
  "type" : "object",
  "properties" : {
    "id" : {
      "$ref" : "#/components/schemas/AlarmId"
    },
    "creationTime" : {
      "$ref" : "#/components/schemas/SO8601Timestamp"
    },
    "timestamp" : {
      "$ref" : "#/components/schemas/SO8601Timestamp"
    },
    "source" : {
      "$ref" : "#/components/schemas/IdObject"
    },
    "type" : {
      "$ref" : "#/components/schemas/AlarmType"
    },
    "text" : {
      "$ref" : "#/components/schemas/AlarmText"
    },
    "severity" : {
      "$ref" : "#/components/schemas/AlarmSeverity"
    },
    "status" : {
      "$ref" : "#/components/schemas/AlarmStatus"
    },
    "assignee" : {
      "$ref" : "#/components/schemas/AlarmAssignee"
    }
  },
  "description" : "The alarm as it is after the event"
}
""",
    object_hook=with_example_provider,
)
alarm_timeline_info_model_schema.update({"definitions": MODEL_DEFINITIONS})

alarm_timeline_info_faker = JSF(
    alarm_timeline_info_model_schema, allow_none_optionals=1
)


class AlarmTimelineInfoStub:
    """AlarmTimelineInfo unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return alarm_timeline_info_faker.generate()

    @classmethod
    def create_instance(cls) -> "AlarmTimelineInfo":
        """Create AlarmTimelineInfo stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        return AlarmTimelineInfoAdapter.validate_python(cls.create_json())
