# coding: utf-8
"""Waylay Alarms model tests.

This code was generated from the OpenAPI documentation of 'Waylay Alarms'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.alarms.models.batch_delete_alarm_all_of_query import (
        BatchDeleteAlarmAllOfQuery,
    )

    BatchDeleteAlarmAllOfQueryAdapter = TypeAdapter(BatchDeleteAlarmAllOfQuery)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

batch_delete_alarm_all_of_query_model_schema = json.loads(
    r"""{
  "title" : "BatchDeleteAlarm_allOf_query",
  "oneOf" : [ {
    "$ref" : "#/components/schemas/BulkQueryIds"
  }, {
    "$ref" : "#/components/schemas/BulkQueryFilter"
  } ]
}
""",
    object_hook=with_example_provider,
)
batch_delete_alarm_all_of_query_model_schema.update({"definitions": MODEL_DEFINITIONS})

batch_delete_alarm_all_of_query_faker = JSF(
    batch_delete_alarm_all_of_query_model_schema, allow_none_optionals=1
)


class BatchDeleteAlarmAllOfQueryStub:
    """BatchDeleteAlarmAllOfQuery unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return batch_delete_alarm_all_of_query_faker.generate()

    @classmethod
    def create_instance(cls) -> "BatchDeleteAlarmAllOfQuery":
        """Create BatchDeleteAlarmAllOfQuery stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        return BatchDeleteAlarmAllOfQueryAdapter.validate_python(cls.create_json())
