# coding: utf-8
"""Waylay Alarms model tests.

This code was generated from the OpenAPI documentation of 'Waylay Alarms'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.alarms.models.batch_delete_alarm_all_of_action import (
        BatchDeleteAlarmAllOfAction,
    )

    BatchDeleteAlarmAllOfActionAdapter = TypeAdapter(BatchDeleteAlarmAllOfAction)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

batch_delete_alarm_all_of_action_model_schema = json.loads(
    r"""{
  "title" : "BatchDeleteAlarm_allOf_action",
  "type" : "string",
  "enum" : [ "delete" ]
}
""",
    object_hook=with_example_provider,
)
batch_delete_alarm_all_of_action_model_schema.update({"definitions": MODEL_DEFINITIONS})

batch_delete_alarm_all_of_action_faker = JSF(
    batch_delete_alarm_all_of_action_model_schema, allow_none_optionals=1
)


class BatchDeleteAlarmAllOfActionStub:
    """BatchDeleteAlarmAllOfAction unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return batch_delete_alarm_all_of_action_faker.generate()

    @classmethod
    def create_instance(cls) -> "BatchDeleteAlarmAllOfAction":
        """Create BatchDeleteAlarmAllOfAction stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        return BatchDeleteAlarmAllOfActionAdapter.validate_python(cls.create_json())
