# coding: utf-8
"""Waylay Alarms model tests.

This code was generated from the OpenAPI documentation of 'Waylay Alarms'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.alarms.models.batch_update_alarm import BatchUpdateAlarm

    BatchUpdateAlarmAdapter = TypeAdapter(BatchUpdateAlarm)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

batch_update_alarm_model_schema = json.loads(
    r"""{
  "required" : [ "action", "actionParameters", "entity", "query" ],
  "type" : "object",
  "allOf" : [ {
    "$ref" : "#/components/schemas/BatchAlarm"
  }, {
    "properties" : {
      "actionParameters" : {
        "$ref" : "#/components/schemas/AlarmUpdate"
      },
      "action" : {
        "$ref" : "#/components/schemas/BatchUpdateAlarm_allOf_action"
      },
      "query" : {
        "$ref" : "#/components/schemas/BulkQueryIds"
      }
    }
  } ]
}
""",
    object_hook=with_example_provider,
)
batch_update_alarm_model_schema.update({"definitions": MODEL_DEFINITIONS})

batch_update_alarm_faker = JSF(batch_update_alarm_model_schema, allow_none_optionals=1)


class BatchUpdateAlarmStub:
    """BatchUpdateAlarm unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return batch_update_alarm_faker.generate()

    @classmethod
    def create_instance(cls) -> "BatchUpdateAlarm":
        """Create BatchUpdateAlarm stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        return BatchUpdateAlarmAdapter.validate_python(cls.create_json())
