# coding: utf-8
"""Waylay Alarms model tests.

This code was generated from the OpenAPI documentation of 'Waylay Alarms'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.alarms.models.batch_alarms_specification import (
        BatchAlarmsSpecification,
    )

    BatchAlarmsSpecificationAdapter = TypeAdapter(BatchAlarmsSpecification)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

batch_alarms_specification_model_schema = json.loads(
    r"""{
  "type" : "object",
  "example" : {
    "entity" : "alarm",
    "action" : "delete",
    "query" : {
      "ids" : [ "2c49e3bf-547b-42bc-a5e9-9193155ec03d" ]
    }
  },
  "oneOf" : [ {
    "$ref" : "#/components/schemas/BatchUpdateAlarm"
  }, {
    "$ref" : "#/components/schemas/BatchDeleteAlarm"
  } ]
}
""",
    object_hook=with_example_provider,
)
batch_alarms_specification_model_schema.update({"definitions": MODEL_DEFINITIONS})

batch_alarms_specification_faker = JSF(
    batch_alarms_specification_model_schema, allow_none_optionals=1
)


class BatchAlarmsSpecificationStub:
    """BatchAlarmsSpecification unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return batch_alarms_specification_faker.generate(
            use_defaults=True, use_examples=True
        )

    @classmethod
    def create_instance(cls) -> "BatchAlarmsSpecification":
        """Create BatchAlarmsSpecification stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if json is None:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                BatchAlarmsSpecificationAdapter.json_schema(), allow_none_optionals=1
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return BatchAlarmsSpecificationAdapter.validate_python(
            json, context={"skip_validation": True}
        )
