# coding: utf-8
"""Waylay Alarms model tests.

This code was generated from the OpenAPI documentation of 'Waylay Alarms'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import datetime
import json
import warnings

from typing import (
    Union,
    List,
    Dict,
    Literal,  # >=3.8
)
from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.alarms.models.batch_delete_alarm import BatchDeleteAlarm

    BatchDeleteAlarmAdapter = TypeAdapter(BatchDeleteAlarm)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

batch_delete_alarm_model_schema = json.loads(
    r"""{
  "required" : [ "action", "entity", "query" ],
  "type" : "object",
  "allOf" : [ {
    "$ref" : "#/components/schemas/BatchAlarm"
  }, {
    "properties" : {
      "action" : {
        "type" : "string",
        "enum" : [ "delete" ]
      },
      "query" : {
        "$ref" : "#/components/schemas/BatchDeleteAlarm_allOf_query"
      }
    }
  } ]
}
""",
    object_hook=with_example_provider,
)
batch_delete_alarm_model_schema.update({"definitions": MODEL_DEFINITIONS})

batch_delete_alarm_faker = JSF(batch_delete_alarm_model_schema, allow_none_optionals=1)


class BatchDeleteAlarmStub:
    """BatchDeleteAlarm unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return batch_delete_alarm_faker.generate()

    @classmethod
    def create_instance(cls) -> "BatchDeleteAlarm":
        """Create BatchDeleteAlarm stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        return BatchDeleteAlarmAdapter.validate_python(cls.create_json())
