# coding: utf-8
"""Waylay Alarms model tests.

This code was generated from the OpenAPI documentation of 'Waylay Alarms'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import datetime
import json
import warnings

from typing import (
    Union,
    List,
    Dict,
    Literal,  # >=3.8
)
from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.alarms.models.bulk_query_ids import BulkQueryIds

    BulkQueryIdsAdapter = TypeAdapter(BulkQueryIds)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

bulk_query_ids_model_schema = json.loads(
    r"""{
  "title" : "BulkQueryIds",
  "required" : [ "ids" ],
  "type" : "object",
  "properties" : {
    "ids" : {
      "title" : "ids",
      "minItems" : 1,
      "type" : "array",
      "items" : {
        "$ref" : "#/components/schemas/AlarmId"
      }
    }
  }
}
""",
    object_hook=with_example_provider,
)
bulk_query_ids_model_schema.update({"definitions": MODEL_DEFINITIONS})

bulk_query_ids_faker = JSF(bulk_query_ids_model_schema, allow_none_optionals=1)


class BulkQueryIdsStub:
    """BulkQueryIds unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return bulk_query_ids_faker.generate()

    @classmethod
    def create_instance(cls) -> "BulkQueryIds":
        """Create BulkQueryIds stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        return BulkQueryIdsAdapter.validate_python(cls.create_json())
