# coding: utf-8
"""Waylay Alarms model tests.

This code was generated from the OpenAPI documentation of 'Waylay Alarms'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.alarms.models.bulk_query_filter import BulkQueryFilter

    BulkQueryFilterAdapter = TypeAdapter(BulkQueryFilter)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

bulk_query_filter_model_schema = json.loads(
    r"""{
  "type" : "object",
  "properties" : {
    "type" : {
      "$ref" : "#/components/schemas/Alarm_Type_Filter"
    },
    "status" : {
      "$ref" : "#/components/schemas/Alarm_Status_Filter"
    },
    "severity" : {
      "$ref" : "#/components/schemas/Alarm_Severity_Filter"
    },
    "source" : {
      "$ref" : "#/components/schemas/Alarm_Source_Filter"
    },
    "dateFrom" : {
      "allOf" : [ {
        "$ref" : "#/components/schemas/UnixEpochMillis"
      }, {
        "title" : "Alarm timestamp filter (>=)"
      } ]
    },
    "dateTo" : {
      "allOf" : [ {
        "$ref" : "#/components/schemas/UnixEpochMillis"
      }, {
        "title" : "Alarm timestamp filter (<=)"
      } ]
    },
    "assignee" : {
      "$ref" : "#/components/schemas/AlarmAssignee"
    },
    "creationTimeFrom" : {
      "allOf" : [ {
        "$ref" : "#/components/schemas/UnixEpochMillis"
      }, {
        "title" : "Alarm creationTime filter (>=)"
      } ]
    },
    "creationTimeTo" : {
      "allOf" : [ {
        "$ref" : "#/components/schemas/UnixEpochMillis"
      }, {
        "title" : "Alarm creationTime filter (<=)"
      } ]
    },
    "lastUpdatedFrom" : {
      "allOf" : [ {
        "$ref" : "#/components/schemas/UnixEpochMillis"
      }, {
        "title" : "Alarm lastUpdateTime filter (>=)"
      } ]
    },
    "lastUpdatedTo" : {
      "allOf" : [ {
        "$ref" : "#/components/schemas/UnixEpochMillis"
      }, {
        "title" : "Alarm lastUpdateTime filter (<=)"
      } ]
    },
    "lastTriggeredFrom" : {
      "allOf" : [ {
        "$ref" : "#/components/schemas/UnixEpochMillis"
      }, {
        "title" : "Alarm lastTriggeredTime filter (>=)"
      } ]
    },
    "lastTriggeredTo" : {
      "allOf" : [ {
        "$ref" : "#/components/schemas/UnixEpochMillis"
      }, {
        "title" : "Alarm lastTriggeredTime filter (<=)"
      } ]
    }
  },
  "description" : "Object specifying filters on the alarm to which the operation will be applied.\nAt least one of the filters must be set."
}
""",
    object_hook=with_example_provider,
)
bulk_query_filter_model_schema.update({"definitions": MODEL_DEFINITIONS})

bulk_query_filter_faker = JSF(bulk_query_filter_model_schema, allow_none_optionals=1)


class BulkQueryFilterStub:
    """BulkQueryFilter unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return bulk_query_filter_faker.generate()

    @classmethod
    def create_instance(cls) -> "BulkQueryFilter":
        """Create BulkQueryFilter stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        return BulkQueryFilterAdapter.validate_python(cls.create_json())
