# coding: utf-8
"""Waylay Alarms model tests.

This code was generated from the OpenAPI documentation of 'Waylay Alarms'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.alarms.models.get_eventstream_event_format_parameter import (
        GetEventstreamEventFormatParameter,
    )

    GetEventstreamEventFormatParameterAdapter = TypeAdapter(
        GetEventstreamEventFormatParameter
    )
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

get_eventstream_event_format_parameter_model_schema = json.loads(
    r"""{
  "type" : "string",
  "enum" : [ "application/cloudevents+json" ]
}
""",
    object_hook=with_example_provider,
)
get_eventstream_event_format_parameter_model_schema.update({
    "definitions": MODEL_DEFINITIONS
})

get_eventstream_event_format_parameter_faker = JSF(
    get_eventstream_event_format_parameter_model_schema, allow_none_optionals=1
)


class GetEventstreamEventFormatParameterStub:
    """GetEventstreamEventFormatParameter unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return get_eventstream_event_format_parameter_faker.generate()

    @classmethod
    def create_instance(cls) -> "GetEventstreamEventFormatParameter":
        """Create GetEventstreamEventFormatParameter stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        return GetEventstreamEventFormatParameterAdapter.validate_python(
            cls.create_json()
        )
