# coding: utf-8
"""Waylay Alarms model tests.

This code was generated from the OpenAPI documentation of 'Waylay Alarms'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.alarms.models.list_sort_parameter import ListSortParameter

    ListSortParameterAdapter = TypeAdapter(ListSortParameter)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

list_sort_parameter_model_schema = json.loads(
    r"""{
  "type" : "string",
  "default" : "timestamp",
  "enum" : [ "timestamp", "lastUpdateTime", "lastTriggeredTime" ]
}
""",
    object_hook=with_example_provider,
)
list_sort_parameter_model_schema.update({"definitions": MODEL_DEFINITIONS})

list_sort_parameter_faker = JSF(
    list_sort_parameter_model_schema, allow_none_optionals=1
)


class ListSortParameterStub:
    """ListSortParameter unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return list_sort_parameter_faker.generate(use_defaults=True, use_examples=True)

    @classmethod
    def create_instance(cls) -> "ListSortParameter":
        """Create ListSortParameter stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if not json:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                ListSortParameterAdapter.json_schema(), allow_none_optionals=1
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return ListSortParameterAdapter.validate_python(
            json, context={"skip_validation": True}
        )
