# coding: utf-8
"""Waylay Alarms model tests.

This code was generated from the OpenAPI documentation of 'Waylay Alarms'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import datetime
import json
import warnings

from typing import (
    Union,
    List,
    Dict,
    Literal,  # >=3.8
)
from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.alarms.models.queued_operation_summary import (
        QueuedOperationSummary,
    )

    QueuedOperationSummaryAdapter = TypeAdapter(QueuedOperationSummary)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

queued_operation_summary_model_schema = json.loads(
    r"""{
  "title" : "Queued operation summary",
  "required" : [ "action", "entity" ],
  "type" : "object",
  "properties" : {
    "entity" : {
      "$ref" : "#/components/schemas/BatchAlarmEntity"
    },
    "action" : {
      "type" : "string",
      "enum" : [ "update", "delete" ]
    }
  }
}
""",
    object_hook=with_example_provider,
)
queued_operation_summary_model_schema.update({"definitions": MODEL_DEFINITIONS})

queued_operation_summary_faker = JSF(
    queued_operation_summary_model_schema, allow_none_optionals=1
)


class QueuedOperationSummaryStub:
    """QueuedOperationSummary unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return queued_operation_summary_faker.generate()

    @classmethod
    def create_instance(cls) -> "QueuedOperationSummary":
        """Create QueuedOperationSummary stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        return QueuedOperationSummaryAdapter.validate_python(cls.create_json())
