# coding: utf-8
"""Waylay Alarms model tests.

This code was generated from the OpenAPI documentation of 'Waylay Alarms'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.alarms.models.queued_operation_summary import (
        QueuedOperationSummary,
    )

    QueuedOperationSummaryAdapter = TypeAdapter(QueuedOperationSummary)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

queued_operation_summary_model_schema = json.loads(
    r"""{
  "title" : "Queued operation summary",
  "required" : [ "action", "entity" ],
  "type" : "object",
  "properties" : {
    "entity" : {
      "$ref" : "#/components/schemas/BatchAlarmEntity"
    },
    "action" : {
      "$ref" : "#/components/schemas/Queued_operation_summary_action"
    }
  }
}
""",
    object_hook=with_example_provider,
)
queued_operation_summary_model_schema.update({"definitions": MODEL_DEFINITIONS})

queued_operation_summary_faker = JSF(
    queued_operation_summary_model_schema, allow_none_optionals=1
)


class QueuedOperationSummaryStub:
    """QueuedOperationSummary unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return queued_operation_summary_faker.generate(
            use_defaults=True, use_examples=True
        )

    @classmethod
    def create_instance(cls) -> "QueuedOperationSummary":
        """Create QueuedOperationSummary stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if json is None:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                QueuedOperationSummaryAdapter.json_schema(), allow_none_optionals=1
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return QueuedOperationSummaryAdapter.validate_python(
            json, context={"skip_validation": True}
        )
