# coding: utf-8
"""Waylay Alarms models.

This code was generated from the OpenAPI documentation of 'Waylay Alarms'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from datetime import datetime
from typing import List

from pydantic import (
    ConfigDict,
    Field,
)
from waylay.sdk.api._models import BaseModel as WaylayBaseModel

from ..models.alarm_event_alarm import AlarmEventAlarm
from ..models.alarm_event_changes_inner import AlarmEventChangesInner
from ..models.alarm_event_type import AlarmEventType


class AlarmEvent(WaylayBaseModel):
    """AlarmEvent."""

    eventtype: AlarmEventType
    eventtime: datetime
    alarm: AlarmEventAlarm
    changes: List[AlarmEventChangesInner] | None = Field(
        default=None,
        description="Describes the changes that where done  Will only be there if `eventtype` is `io.waylay.alarm.AlarmUpdated`",
    )

    model_config = ConfigDict(
        populate_by_name=True, protected_namespaces=(), extra="ignore"
    )
