# coding: utf-8
"""Waylay Alarms models.

This code was generated from the OpenAPI documentation of 'Waylay Alarms'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from pydantic import (
    ConfigDict,
    Field,
    StrictStr,
)
from waylay.sdk.api._models import BaseModel as WaylayBaseModel

from ..models.alarm_event_changes_inner_type import AlarmEventChangesInnerType


class AlarmEventChangesInner(WaylayBaseModel):
    """AlarmEventChangesInner."""

    attribute: StrictStr | None = None
    type: AlarmEventChangesInnerType | None = None
    old_value: StrictStr | None = Field(default=None, alias="oldValue")
    new_value: StrictStr | None = Field(default=None, alias="newValue")

    model_config = ConfigDict(
        populate_by_name=True, protected_namespaces=(), extra="ignore"
    )
