# coding: utf-8
"""Waylay Alarms models.

This code was generated from the OpenAPI documentation of 'Waylay Alarms'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from pydantic import (
    ConfigDict,
    Field,
    StrictInt,
)
from waylay.sdk.api._models import BaseModel as WaylayBaseModel

from ..models.alarm_event_type import AlarmEventType
from ..models.alarm_timeline_info import AlarmTimelineInfo


class AlarmsTimelineItem(WaylayBaseModel):
    """AlarmsTimelineItem."""

    timestamp: StrictInt = Field(description="Timestamp of the event")
    type: AlarmEventType
    alarm: AlarmTimelineInfo

    model_config = ConfigDict(
        populate_by_name=True, protected_namespaces=(), extra="ignore"
    )
