# coding: utf-8
"""Waylay Alarms models.

This code was generated from the OpenAPI documentation of 'Waylay Alarms'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from datetime import datetime

from pydantic import (
    ConfigDict,
    Field,
    StrictStr,
)
from waylay.sdk.api._models import BaseModel as WaylayBaseModel

from ..models.queued_operation_summary import QueuedOperationSummary


class BatchOperationEnqueuedEntity(WaylayBaseModel):
    """BatchOperationEnqueuedEntity."""

    id: StrictStr
    queue_time: datetime = Field(alias="queueTime")
    operation: QueuedOperationSummary

    model_config = ConfigDict(
        populate_by_name=True, protected_namespaces=(), extra="ignore"
    )
