# coding: utf-8
"""Waylay Alarms models.

This code was generated from the OpenAPI documentation of 'Waylay Alarms'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from enum import Enum


class CloudAlarmEventDataType(str, Enum):
    """CloudAlarmEventDataType."""

    IO_DOT_WAYLAY_DOT_ALARMS_DOT_V1_DOT_ALARM_RAISED = "io.waylay.alarms.v1.AlarmRaised"
    IO_DOT_WAYLAY_DOT_ALARMS_DOT_V1_DOT_EVENT_OCCURRED_AGAIN = (
        "io.waylay.alarms.v1.EventOccurredAgain"
    )
    IO_DOT_WAYLAY_DOT_ALARMS_DOT_V1_DOT_ALARM_UPDATED = (
        "io.waylay.alarms.v1.AlarmUpdated"
    )

    def __str__(self) -> str:
        return str(self.value)
