# coding: utf-8
"""Waylay Alarms models.

This code was generated from the OpenAPI documentation of 'Waylay Alarms'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from pydantic import (
    ConfigDict,
)
from waylay.sdk.api._models import BaseModel as WaylayBaseModel

from ..models.batch_alarm_entity import BatchAlarmEntity
from ..models.queued_operation_summary_action import QueuedOperationSummaryAction


class QueuedOperationSummary(WaylayBaseModel):
    """QueuedOperationSummary."""

    entity: BatchAlarmEntity
    action: QueuedOperationSummaryAction

    model_config = ConfigDict(
        populate_by_name=True, protected_namespaces=(), extra="ignore"
    )
