# coding: utf-8
"""Waylay Alarms models.

This code was generated from the OpenAPI documentation of 'Waylay Alarms'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from datetime import datetime
from typing import (
    Union,
)

from typing_extensions import (
    Annotated,  # >=3.9
)

SO8601TimestampOrMillis = Union[
    Annotated[
        int,
        "Timestamp expressed as milliseconds since 00:00:00 UTC on 1 January 1970,  not counting leap seconds.",
    ],
    Annotated[datetime, ""],
]
"""ISO8601 timestamp or unix epoch milliseconds.."""
